defmodule FirmwareManager.Repo.Migrations.CreateCmts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cmts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :modem_snmp_write, :text, null: false
      add :modem_snmp_read, :text, null: false
      add :snmp_read, :text, null: false
      add :ip, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:cmts)
  end
end