defmodule FirmwareManager.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:upgrade_logs, primary_key: false) do
      add :upgraded_at, :utc_datetime, null: false
      add :new_firmware, :text, null: false
      add :new_sysdescr, :text, null: false
      add :old_sysdescr, :text, null: false
      add :mac_address, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:upgrade_logs, [:mac_address], name: "upgrade_logs_by_mac_address_index")
  end

  def down do
    drop_if_exists unique_index(:upgrade_logs, [:mac_address],
                     name: "upgrade_logs_by_mac_address_index"
                   )

    drop table(:upgrade_logs)
  end
end
