name: Build and publish container (Podman)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Podman
        uses: redhat-actions/podman-setup@v2
        with:
          podman_version: latest

      - name: Install qemu-user-static for cross-arch
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Log in to GHCR (Podman)
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (linux/arm64) with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ github.sha }}
          context: .
          containerfiles: |
            ./Dockerfile
          extra-args: |
            --platform linux/arm64

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ github.sha }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
